### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by icepick3000** [kuzmoyev/google-calendar-simple-api#143]
Does this python script need some kind of webserver to run? 
```
Traceback (most recent call last):
  File "gc.py", line 3, in <module>
    calendar = GoogleCalendar('pantalondusud@gmail.com')
  File "/usr/local/lib/python3.7/dist-packages/gcsa/google_calendar.py", line 97, in __init__
    authentication_flow_port
  File "/usr/local/lib/python3.7/dist-packages/gcsa/google_calendar.py", line 131, in _get_credentials
    credentials = flow.run_local_server(host=host, port=port)
  File "/usr/local/lib/python3.7/dist-packages/google_auth_oauthlib/flow.py", line 458, in run_local_server
    host, port, wsgi_app, handler_class=_WSGIRequestHandler
  File "/usr/lib/python3.7/wsgiref/simple_server.py", line 153, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Comment by kuzmoyev** [comment]
It runs its own server for the authentication flow. This error probably means that the default port (8080) is occupied by something else. A quick fix would be to set a different port:

```
calendar = GoogleCalendar('pantalondusud@gmail.com', authentication_flow_port=8081)
```

But you should check what process uses the 8080 port

**Comment by icepick3000** [comment]
Yup, that worked.. ran into other issues after that.. but eventually got it to work, thanks for your quick reply!
