### ISSUE TITLE
'Credentials' object has no attribute 'refresh_token'. (Support service accounts)

### ISSUE THREAD

**Issue by one2gov** [kuzmoyev/google-calendar-simple-api#157]
```
2022-12-05 21:58:10 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-657' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'Credentials' object has no attribute 'refresh_token'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "rig_1_timetable_tg_bot.py", line 432, in check_callback_filter
    global software_str
  File "rig_1_timetable_tg_bot.py", line 526, in new_render_tz
  File "/usr/local/lib/python3.8/site-packages/gcsa/google_calendar.py", line 62, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/site-packages/gcsa/_services/base_service.py", line 18, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/gcsa/_services/authentication.py", line 53, in __init__
    self.credentials = self._ensure_refreshed(credentials)
  File "/usr/local/lib/python3.8/site-packages/gcsa/_services/authentication.py", line 76, in _ensure_refreshed
    if not credentials.valid and credentials.expired and credentials.refresh_token:
AttributeError: 'Credentials' object has no attribute 'refresh_token'
```

Hello, I am using "service account" generated json, as a credential file. token.pickle is not created, I am getting this error every hour. 

```
SCOPES = ["https://www.googleapis.com/auth/calendar", 'https://www.googleapis.com/auth/calendar.events',
          'https://www.googleapis.com/auth/calendar.events.readonly',
          'https://www.googleapis.com/auth/calendar.readonly',
          'https://www.googleapis.com/auth/calendar.settings.readonly']
SERVICE_ACCOUNT_FILE = 'credentials.json'

credentials = service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE, scopes=SCOPES)

global calendar, calendarListTransform, calendarListTransform
calendar = GoogleCalendar('email', credentials=credentials)

```

**Comment by kuzmoyev** [comment]
Hi, please include the imports. Are you using `oauth2client` or `google.oauth2`?

**Comment by kuzmoyev** [comment]
Now I realized that `service_account.Credentials` is different from `credentials.Credentials` hence the error. Service accounts are not directly supported by gcsa yet. But as a workaround you should be able to refresh it yourself with the following:

```python
from google.auth.transport.requests import Request
...

if credentials.expired:
    credentials.refresh(Request())

calendar = GoogleCalendar('email', credentials=credentials)
```
