### ISSUE TITLE
Circular Import Error

### ISSUE THREAD

**Issue by brandonbarringer** [kuzmoyev/google-calendar-simple-api#170]
## Bug description

Creates a circular import error when importing the GoogleCalendar class

## To Reproduce

1. Installed the latest version with `pipenv install gcsa`
2. Import the GoogleCalendar class

Code used:

```python
from gcsa.google_calendar import GoogleCalendar
import os.path

path = os.path.dirname(os.path.abspath(__file__))
credentials_path = os.path.join(path, 'private/credentials.json')
gc = GoogleCalendar(credentials_path=credentials_path)

if __name__ == '__main__':
    for calendar in gc.get_calendar_list():
        print(calendar)

...
```

## Error or unexpected output

The whole traceback in case of an error:
```
Traceback (most recent call last):
  File "/Users/brandonbarringer/Desktop/python/echo.gpt/services/calendar.py", line 1, in <module>
    from gcsa.google_calendar import GoogleCalendar
  File "/Users/brandonbarringer/.local/share/virtualenvs/echo.gpt-d-RNtiyj/lib/python3.10/site-packages/gcsa/google_calendar.py", line 1, in <module>
    from google.oauth2.credentials import Credentials
  File "/Users/brandonbarringer/.local/share/virtualenvs/echo.gpt-d-RNtiyj/lib/python3.10/site-packages/google/oauth2/credentials.py", line 41, in <module>
    from google.auth import _cloud_sdk
  File "/Users/brandonbarringer/.local/share/virtualenvs/echo.gpt-d-RNtiyj/lib/python3.10/site-packages/google/auth/__init__.py", line 20, in <module>
    from google.auth._default import default, load_credentials_from_file
  File "/Users/brandonbarringer/.local/share/virtualenvs/echo.gpt-d-RNtiyj/lib/python3.10/site-packages/google/auth/_default.py", line 30, in <module>
    import google.auth.transport._http_client
  File "/Users/brandonbarringer/.local/share/virtualenvs/echo.gpt-d-RNtiyj/lib/python3.10/site-packages/google/auth/transport/__init__.py", line 30, in <module>
    from six.moves import http_client
  File "/Users/brandonbarringer/.local/share/virtualenvs/echo.gpt-d-RNtiyj/lib/python3.10/site-packages/six.py", line 97, in __get__
    result = self._resolve()
  File "/Users/brandonbarringer/.local/share/virtualenvs/echo.gpt-d-RNtiyj/lib/python3.10/site-packages/six.py", line 120, in _resolve
    return _import_module(self.mod)
  File "/Users/brandonbarringer/.local/share/virtualenvs/echo.gpt-d-RNtiyj/lib/python3.10/site-packages/six.py", line 87, in _import_module
    __import__(name)
  File "/Users/brandonbarringer/.pyenv/versions/3.10.9/lib/python3.10/http/client.py", line 71, in <module>
    import email.parser
  File "/Users/brandonbarringer/.pyenv/versions/3.10.9/lib/python3.10/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/Users/brandonbarringer/.pyenv/versions/3.10.9/lib/python3.10/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/Users/brandonbarringer/.pyenv/versions/3.10.9/lib/python3.10/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/Users/brandonbarringer/.pyenv/versions/3.10.9/lib/python3.10/email/utils.py", line 33, in <module>
    from email._parseaddr import quote
  File "/Users/brandonbarringer/.pyenv/versions/3.10.9/lib/python3.10/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/Users/brandonbarringer/Desktop/python/echo.gpt/services/calendar.py", line 1, in <module>
    from gcsa.google_calendar import GoogleCalendar
ImportError: cannot import name 'GoogleCalendar' from partially initialized module 'gcsa.google_calendar' (most likely due to a circular import) (/Users/brandonbarringer/.local/share/virtualenvs/echo.gpt-d-RNtiyj/lib/python3.10/site-packages/gcsa/google_calendar.py)
...
```

## Tech:

- OS: MacOS
- GCSA version: latest
- Python version: 3.10.9

**Comment by kuzmoyev** [comment]
Hi!

It looks like your script `calendar.py` collides with Python's built-in module `calendar` that is used somewhere in the depth of the `google-auth` library. Can you rename your script to something else and try again?

**Comment by kuzmoyev** [comment]
Closing due to inactivity.

If you have resolved the issue, please let us know. If not, feel free to add more details here, start a new GitHub Discussion, or reach out on Discord.
