### ISSUE TITLE
gadget_serializer: KeyError when fetching events from Contacts calendar

### ISSUE THREAD

**Issue by eitchtee** [kuzmoyev/google-calendar-simple-api#44]
Google Calendar has a built-in calendar called "Contacts" (id: addressbook#contacts@group.v.calendar.google.com) that syncs with some data like birthdays from Google Contacts, but these events seems to be somewhat special as their gadget-JSON is different from others, as it is missing most paramentes:

```{'iconLink': 'https://calendar.google.com/googlecalendar/images/cake.gif', 'preferences': {'goo.contactsGivenName': 'Isabela', 'goo.contactsEventType': 'BIRTHDAY', 'goo.contactsFullName': 'Isabela', 'goo.isGPlusUser': 'false', 'goo.contactsContactId': '123a4b5c6d89efgh', 'goo.contactsIsMyContact': 'true'}}```

This difference means GCSA raises an Exception when serializing such events:

```Traceback (most recent call last):
  File "C:/Users/eitch/PycharmProjects/gcal2todoist/code/scratch.py", line 11, in <module>
    for event in a:
  File "C:\Users\eitch\PycharmProjects\gcal2todoist\venv\lib\site-packages\gcsa\google_calendar.py", line 183, in get_events
    event = EventSerializer(event_json).get_object()
  File "C:\Users\eitch\PycharmProjects\gcal2todoist\venv\lib\site-packages\gcsa\serializers\base_serializer.py", line 20, in get_object
    return self.to_object(self.data)
  File "C:\Users\eitch\PycharmProjects\gcal2todoist\venv\lib\site-packages\gcsa\serializers\base_serializer.py", line 38, in to_object
    return cls._to_object(json_)
  File "C:\Users\eitch\PycharmProjects\gcal2todoist\venv\lib\site-packages\gcsa\serializers\event_serializer.py", line 94, in _to_object
    gadget = GadgetSerializer.to_object(gadget_json) if gadget_json else None
  File "C:\Users\eitch\PycharmProjects\gcal2todoist\venv\lib\site-packages\gcsa\serializers\base_serializer.py", line 38, in to_object
    return cls._to_object(json_)
  File "C:\Users\eitch\PycharmProjects\gcal2todoist\venv\lib\site-packages\gcsa\serializers\gadget_serializer.py", line 34, in _to_object
    title=json_gadget['title'],
KeyError: 'title'
```

**Comment by eitchtee** [comment]
A simple way to fix this would be to use .get() on all gadget's JSON entries, but the Gadget class checks if some parameters are empty, is there a benefit for this check?

With your help I can prep a quick pull request.

**Comment by kuzmoyev** [comment]
Didn't know about it. Than you for the issue submission.

As this is the case, I think we can use `.get()` and remove any checks in `Gadget`. I'd need to check the official docs first. But will be really grateful for a PR

**Comment by eitchtee** [comment]
Done. I've decided to build a simple workaround for the gadget_serializer itself, meaning that the empty checks still happens when adding a Gadget to an Event.

Hope you like it. Looking forward to see this patched.
